[package]
name = "hecto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
tree-sitter = "0.20.9"
unicode-segmentation = "1"

[build-dependencies]
cc="1.0"
